---
- name: Ensure fonts directory exists.
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory
    mode: 0777

- name: Ensure directory for each font exists.
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.fonts/{{ item }}"
    state: directory
    mode: 0777
  loop:
    - "JetBrainsMono"

- name: Install fonts.
  ansible.builtin.unarchive:
    src: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/{{ item }}.zip"
    dest: "{{ lookup('env', 'HOME') }}/.fonts/{{ item }}"
    remote_src: true
  loop:
    - "JetBrainsMono"
