---
# tasks file for ssh
- name: Generate ssh keys.
  ansible.builtin.command:
    cmd: |
      ssh-keygen -q -t ed25519
      -C "{{ item.email }}"
      -N ""
      -f "{{ lookup('env', 'HOME') }}/.ssh/id_{{ item.id }}"
    creates: "{{ lookup('env', 'HOME') }}/.ssh/id_{{ item.id }}"
  with_items:
    - "{{ git_emails }}"
